services:
  app:
    image: kadxy/api-grip-server:latest
    container_name: api-grip-server
    ports:
      - "9527:9527"
    environment:
      - NODE_ENV=production
      - PORT=9527
      - LISTEN_HOST=0.0.0.0
    env_file:
      - .env
    restart: unless-stopped
